import { randomUUID } from 'node:crypto';import { join } from 'node:path';import cookie from '@fastify/cookie';import helmet from '@fastify/helmet';import rateLimit from '@fastify/rate-limit';import staticPlugin from '@fastify/static';import Fastify from 'fastify';import { z } from 'zod';import { authenticate,changeAccount,login,logout } from './auth.js';import { config } from './config.js';import { pool } from './db/pool.js';
const error=(code:string,message:string,fieldErrors?:Record<string,string>)=>({error:{code,message,fieldErrors,correlationId:randomUUID()}});
function sameOrigin(request:any,reply:any,done:any){if(['POST','PATCH','PUT','DELETE'].includes(request.method)){const origin=request.headers.origin;if(origin&&origin!==config.PUBLIC_ORIGIN&&!(config.NODE_ENV!=='production'&&origin.startsWith('http://localhost'))){reply.code(403).send(error('ORIGIN_REJECTED','The request origin is not allowed.'));return;}}done();}
export async function buildApp(){const app=Fastify({logger:{level:config.NODE_ENV==='production'?'info':'warn',redact:['req.headers.authorization','req.headers.cookie']},bodyLimit:131072});await app.register(cookie);await app.register(rateLimit,{max:100,timeWindow:'1 minute'});await app.register(helmet,{global:true,contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'","'wasm-unsafe-eval'"],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'",'data:'],connectSrc:["'self'"]}}});app.addHook('preHandler',sameOrigin);
 app.get('/health/live',async()=>({status:'ok'}));app.get('/health/ready',async(_q,r)=>{try{await pool.query('SELECT 1');return {status:'ready'};}catch{return r.code(503).send({status:'unavailable'});}});
 app.get('/app/catalog',async()=>{const r=await pool.query('SELECT snapshot FROM catalog_snapshots ORDER BY published_at DESC LIMIT 1');return r.rows[0]?.snapshot??{version:'unavailable',roles:[]};});app.get('/app/config',async()=>{const r=await pool.query('SELECT donation_url,ads_enabled FROM site_settings WHERE id=1');return r.rows[0]??{donation_url:null,ads_enabled:false};});
 const roleRequest=z.object({roleTitle:z.string().trim().min(2).max(100),seniority:z.string().max(30).optional(),industry:z.string().max(200).optional(),desiredSkills:z.string().max(500).optional(),replyEmail:z.string().email().max(254).optional().or(z.literal('')),website:z.literal('').optional()}).strict();app.post('/app/role-requests',{config:{rateLimit:{max:5,timeWindow:'1 hour'}}},async(req,reply)=>{const parsed=roleRequest.safeParse(req.body);if(!parsed.success)return reply.code(400).send(error('VALIDATION_ERROR','One or more fields are invalid.'));const v=parsed.data;await pool.query('INSERT INTO role_requests(role_title,seniority,industry,desired_skills,reply_email) VALUES($1,$2,$3,$4,$5)',[v.roleTitle,v.seniority??null,v.industry??null,v.desiredSkills??null,v.replyEmail||null]);return reply.code(202).send({accepted:true});});
 const credentials=z.object({username:z.string().min(3).max(64),password:z.string().min(8).max(256)}).strict();app.post('/app/admin/login',{config:{rateLimit:{max:8,timeWindow:'15 minutes'}}},async(req,reply)=>{const parsed=credentials.safeParse(req.body);if(!parsed.success)return reply.code(401).send(error('INVALID_CREDENTIALS','Invalid username or password.'));const session=await login(parsed.data.username,parsed.data.password);if(!session)return reply.code(401).send(error('INVALID_CREDENTIALS','Invalid username or password.'));reply.setCookie(config.SESSION_COOKIE_NAME,session.token,{path:'/',httpOnly:true,secure:config.NODE_ENV==='production',sameSite:'strict',expires:session.expires});return {signedIn:true,forcePasswordChange:session.forcePasswordChange};});
 app.get('/app/admin/session',{preHandler:authenticate},async req=>({signedIn:true,forcePasswordChange:req.admin!.forcePasswordChange}));app.post('/app/admin/logout',{preHandler:authenticate},async(req,reply)=>{await logout(req.cookies[config.SESSION_COOKIE_NAME]);reply.clearCookie(config.SESSION_COOKIE_NAME,{path:'/'});return {signedIn:false};});
 const account=z.object({currentPassword:z.string().min(8).max(256),newUsername:z.string().regex(/^[a-zA-Z0-9._-]{3,64}$/).optional(),newPassword:z.string().min(12).max(256).optional(),confirmPassword:z.string().optional()}).strict().refine(v=>v.newUsername||v.newPassword,{message:'No change requested'}).refine(v=>!v.newPassword||v.newPassword===v.confirmPassword,{message:'Passwords do not match'});app.patch('/app/admin/account',{preHandler:authenticate},async(req,reply)=>{const parsed=account.safeParse(req.body);if(!parsed.success)return reply.code(400).send(error('VALIDATION_ERROR','One or more fields are invalid.'));if(!await changeAccount(parsed.data.currentPassword,parsed.data.newUsername,parsed.data.newPassword))return reply.code(401).send(error('INVALID_CREDENTIALS','Current password is incorrect.'));reply.clearCookie(config.SESSION_COOKIE_NAME,{path:'/'});return {signedIn:false,sessionsRevoked:true};});
 app.get('/app/admin/dashboard',{preHandler:authenticate},async()=>{const [requests,roles,events]=await Promise.all([pool.query('SELECT count(*)::int total,count(*) FILTER(WHERE status=\'new\')::int new FROM role_requests'),pool.query("SELECT count(*)::int total FROM job_roles WHERE archived_at IS NULL"),pool.query('SELECT count(*)::int total FROM aggregate_events')]);return {roleRequests:requests.rows[0],roles:roles.rows[0],aggregateEvents:events.rows[0]};});app.get('/app/admin/role-requests',{preHandler:authenticate},async()=>({items:(await pool.query('SELECT id,role_title,seniority,industry,status,created_at FROM role_requests ORDER BY created_at DESC LIMIT 200')).rows}));app.get('/app/admin/audit-logs',{preHandler:authenticate},async()=>({items:(await pool.query('SELECT id,action,summary,created_at FROM audit_logs ORDER BY created_at DESC LIMIT 200')).rows}));
 await app.register(staticPlugin,{root:join(process.cwd(),'public'),wildcard:false});app.setNotFoundHandler((req,reply)=>req.url.startsWith('/app/')||req.url.startsWith('/health/')?reply.code(404).send(error('NOT_FOUND','Not found.')):reply.sendFile('index.html'));return app;}
